/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;



import Model.Kullanici;
import Presenter.AnaFormPresenter;
import java.awt.Desktop;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;


/**
 *
 * @author kopek
 */
public class Ana_Form extends javax.swing.JFrame implements IViewAnaForm{

    private static Ana_Form formOlustur = new Ana_Form();
    private AnaFormPresenter presenter;
    public static boolean girisVar =false;
    public static Ana_Form yeniFormOlustur(){
        return formOlustur;
    }
    /**
     * Creates new form Ana_Form
     */
   
    static String   user=null;
    private Ana_Form() {
        

       
       
        setIcon();
      
        initComponents();
         
       presenter = new AnaFormPresenter(this);
       presenter.FormGirisi();
       BilgiYaz();
             
     
    }

    public static JTabbedPane getTabbed_Menu() {
        return tabbed_Menu;
    }

    public static void setTabbed_Menu(JTabbedPane tabbed_Menu) {
        Ana_Form.tabbed_Menu = tabbed_Menu;
    }

    public static String getUser() {
        return user;
    }

    public static void setUser(String user) {
        Ana_Form.user = user;
    }




    public static JLabel getLb_user() {
        return lb_user;
    }

    public static void setLb_user(JLabel lb_user) {
        Ana_Form.lb_user = lb_user;
    }










   

 

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon res= new ImageIcon(getClass().getResource("/image/bg.jpg"));
        Image img = res.getImage();
        mdi_Panel = new javax.swing.JDesktopPane(){

            public void paintComponent (Graphics g){
                g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
            }
        };
        tabbed_Menu = new javax.swing.JTabbedPane();
        panel_Kullanici = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_Kullanici_Guncelle = new javax.swing.JButton();
        btn_Ders_Guncelle = new javax.swing.JButton();
        btn_Zorluk_Guncelle = new javax.swing.JButton();
        panel_Ders = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panel_Soru = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_Soru_Turu = new javax.swing.JButton();
        btn_Soru_Guncelle = new javax.swing.JButton();
        panel_Sinav = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_Soru_Turu1 = new javax.swing.JButton();
        btn_Soru_Guncelle2 = new javax.swing.JButton();
        panel_Sifre = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_Sifre = new javax.swing.JButton();
        panel_Proje = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lb_user = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SORU HAZIRLAMA V-1.0");
        setSize(new java.awt.Dimension(1270, 750));

        tabbed_Menu.setToolTipText("");
        tabbed_Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabbed_Menu.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        tabbed_Menu.setMinimumSize(new java.awt.Dimension(300, 201));
        tabbed_Menu.setName("ANA FORM"); // NOI18N
        tabbed_Menu.setVerifyInputWhenFocusTarget(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/muh_logo2.png"))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dpu_logo2.png"))); // NOI18N

        btn_Kullanici_Guncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kullacigi_guncelle.png"))); // NOI18N
        btn_Kullanici_Guncelle.setText("Kullanıcı Guncelle");
        btn_Kullanici_Guncelle.setActionCommand("Kullanıcı Güncelle");
        btn_Kullanici_Guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Kullanici_GuncelleActionPerformed(evt);
            }
        });

        btn_Ders_Guncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ders_guncelle.png"))); // NOI18N
        btn_Ders_Guncelle.setText("Ders Güncelle");
        btn_Ders_Guncelle.setActionCommand("Kullanıcı Güncelle");
        btn_Ders_Guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ders_GuncelleActionPerformed(evt);
            }
        });

        btn_Zorluk_Guncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/zorluk.png"))); // NOI18N
        btn_Zorluk_Guncelle.setText("Zorluk Dereceleri");
        btn_Zorluk_Guncelle.setActionCommand("Kullanıcı Güncelle");
        btn_Zorluk_Guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Zorluk_GuncelleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_KullaniciLayout = new javax.swing.GroupLayout(panel_Kullanici);
        panel_Kullanici.setLayout(panel_KullaniciLayout);
        panel_KullaniciLayout.setHorizontalGroup(
            panel_KullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_KullaniciLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Kullanici_Guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Ders_Guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Zorluk_Guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 400, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_KullaniciLayout.setVerticalGroup(
            panel_KullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_KullaniciLayout.createSequentialGroup()
                .addGroup(panel_KullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panel_KullaniciLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panel_KullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Kullanici_Guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Ders_Guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Zorluk_Guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbed_Menu.addTab("TANIMLAMA İŞLEMLERİ", new javax.swing.ImageIcon(getClass().getResource("/image/ayar.png")), panel_Kullanici); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dpu_logo2.png"))); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/muh_logo2.png"))); // NOI18N

        javax.swing.GroupLayout panel_DersLayout = new javax.swing.GroupLayout(panel_Ders);
        panel_Ders.setLayout(panel_DersLayout);
        panel_DersLayout.setHorizontalGroup(
            panel_DersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_DersLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 988, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );
        panel_DersLayout.setVerticalGroup(
            panel_DersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_DersLayout.createSequentialGroup()
                .addGroup(panel_DersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabbed_Menu.addTab("DERS İŞLEMLERİ", new javax.swing.ImageIcon(getClass().getResource("/image/ders.png")), panel_Ders); // NOI18N

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dpu_logo2.png"))); // NOI18N

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/muh_logo2.png"))); // NOI18N

        btn_Soru_Turu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/soru_turu.png"))); // NOI18N
        btn_Soru_Turu.setText("Soru Listesi");
        btn_Soru_Turu.setActionCommand("Kullanıcı Güncelle");
        btn_Soru_Turu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Soru_TuruActionPerformed(evt);
            }
        });

        btn_Soru_Guncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/soru_guncelle.png"))); // NOI18N
        btn_Soru_Guncelle.setText("Soru Güncelleme");
        btn_Soru_Guncelle.setActionCommand("Kullanıcı Güncelle");
        btn_Soru_Guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Soru_GuncelleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_SoruLayout = new javax.swing.GroupLayout(panel_Soru);
        panel_Soru.setLayout(panel_SoruLayout);
        panel_SoruLayout.setHorizontalGroup(
            panel_SoruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_SoruLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(btn_Soru_Turu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Soru_Guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 594, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );
        panel_SoruLayout.setVerticalGroup(
            panel_SoruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_SoruLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panel_SoruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Soru_Turu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Soru_Guncelle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabbed_Menu.addTab("SORU İŞLEMLERİ", new javax.swing.ImageIcon(getClass().getResource("/image/soru.png")), panel_Soru); // NOI18N

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dpu_logo2.png"))); // NOI18N

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/muh_logo2.png"))); // NOI18N

        btn_Soru_Turu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/soru_turu.png"))); // NOI18N
        btn_Soru_Turu1.setText("Sınav Listesi");
        btn_Soru_Turu1.setToolTipText("");
        btn_Soru_Turu1.setActionCommand("Kullanıcı Güncelle");
        btn_Soru_Turu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Soru_Turu1ActionPerformed(evt);
            }
        });

        btn_Soru_Guncelle2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sinav_guncelle.png"))); // NOI18N
        btn_Soru_Guncelle2.setText("Sınav Güncelleme");
        btn_Soru_Guncelle2.setActionCommand("Kullanıcı Güncelle");
        btn_Soru_Guncelle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Soru_Guncelle2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_SinavLayout = new javax.swing.GroupLayout(panel_Sinav);
        panel_Sinav.setLayout(panel_SinavLayout);
        panel_SinavLayout.setHorizontalGroup(
            panel_SinavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_SinavLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(65, 65, 65)
                .addComponent(btn_Soru_Turu1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btn_Soru_Guncelle2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 505, Short.MAX_VALUE)
                .addComponent(jLabel8))
        );
        panel_SinavLayout.setVerticalGroup(
            panel_SinavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_SinavLayout.createSequentialGroup()
                .addGroup(panel_SinavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_SinavLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_SinavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Soru_Turu1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Soru_Guncelle2))
                .addGap(26, 26, 26))
        );

        tabbed_Menu.addTab("SINAV İŞLEMLERİ", new javax.swing.ImageIcon(getClass().getResource("/image/sinav.png")), panel_Sinav); // NOI18N

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dpu_logo2.png"))); // NOI18N

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/muh_logo2.png"))); // NOI18N

        btn_Sifre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sifre_degistir.png"))); // NOI18N
        btn_Sifre.setText("Şifre Değiştir");
        btn_Sifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SifreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_SifreLayout = new javax.swing.GroupLayout(panel_Sifre);
        panel_Sifre.setLayout(panel_SifreLayout);
        panel_SifreLayout.setHorizontalGroup(
            panel_SifreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_SifreLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 806, Short.MAX_VALUE)
                .addComponent(jLabel13))
        );
        panel_SifreLayout.setVerticalGroup(
            panel_SifreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_SifreLayout.createSequentialGroup()
                .addGroup(panel_SifreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panel_SifreLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btn_Sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbed_Menu.addTab("ŞİFRE İŞLEMLERİ", new javax.swing.ImageIcon(getClass().getResource("/image/sifre-1.png")), panel_Sifre); // NOI18N

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/muh_logo2.png"))); // NOI18N
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dpu_logo2.png"))); // NOI18N

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/created.png"))); // NOI18N
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel11.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout panel_ProjeLayout = new javax.swing.GroupLayout(panel_Proje);
        panel_Proje.setLayout(panel_ProjeLayout);
        panel_ProjeLayout.setHorizontalGroup(
            panel_ProjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ProjeLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9))
        );
        panel_ProjeLayout.setVerticalGroup(
            panel_ProjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ProjeLayout.createSequentialGroup()
                .addGroup(panel_ProjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        tabbed_Menu.addTab("PROJE BİLGİLERİ", new javax.swing.ImageIcon(getClass().getResource("/image/uye.png")), panel_Proje); // NOI18N

        lb_user.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_user.setForeground(new java.awt.Color(102, 102, 102));
        lb_user.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        lb_user.setText("Kullanıcı");
        lb_user.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lb_user.setIconTextGap(6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mdi_Panel)
            .addComponent(tabbed_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_user, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbed_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mdi_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbed_Menu.getAccessibleContext().setAccessibleName("");

        setSize(new java.awt.Dimension(1209, 797));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SifreActionPerformed
        // TODO add your handling code here:
        Sifre_Form frm = Sifre_Form.yeniFormOlustur();
        mdi_Panel.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_btn_SifreActionPerformed

    private void btn_Kullanici_GuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Kullanici_GuncelleActionPerformed
        // TODO add your handling code here:
          Kullanici_Guncelle_Form frm =  Kullanici_Guncelle_Form.yeniFormOlustur();
        mdi_Panel.add(frm);
       frm.setVisible(true);
    }//GEN-LAST:event_btn_Kullanici_GuncelleActionPerformed

    private void btn_Ders_GuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ders_GuncelleActionPerformed
        // TODO add your handling code here:
      Ders_Guncelle_Form frm= Ders_Guncelle_Form.yeniFormOlustur();
     
        mdi_Panel.add(frm);
       frm.setVisible(true);
       
    }//GEN-LAST:event_btn_Ders_GuncelleActionPerformed

    private void btn_Zorluk_GuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Zorluk_GuncelleActionPerformed
        // TODO add your handling code here:
        Zorluk_Guncelle_Form frm = Zorluk_Guncelle_Form.yeniFormOlustur();
       
        mdi_Panel.add(frm);
       frm.setVisible(true);
    }//GEN-LAST:event_btn_Zorluk_GuncelleActionPerformed

    private void btn_Soru_TuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Soru_TuruActionPerformed
        // TODO add your handling code here:
        Soru_Liste_Form frm =  Soru_Liste_Form.yeniFormOlustur();
        mdi_Panel.add(frm);
       frm.setVisible(true);
    }//GEN-LAST:event_btn_Soru_TuruActionPerformed

    private void btn_Soru_GuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Soru_GuncelleActionPerformed
        // TODO add your handling code here:
          Soru_Guncelle_Form frm =  Soru_Guncelle_Form.yeniFormOlustur();
             mdi_Panel.add(frm);
       frm.setVisible(true);
    }//GEN-LAST:event_btn_Soru_GuncelleActionPerformed

    private void btn_Soru_Turu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Soru_Turu1ActionPerformed
  Sinav_Listele_Form frm =  Sinav_Listele_Form.yeniFormOlustur();
             mdi_Panel.add(frm);
       frm.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_btn_Soru_Turu1ActionPerformed

    private void btn_Soru_Guncelle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Soru_Guncelle2ActionPerformed
 Sinav_Olustur_Form frm =  Sinav_Olustur_Form.yeniFormOlustur();
             mdi_Panel.add(frm);
       frm.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_btn_Soru_Guncelle2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ana_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ana_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ana_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ana_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ana_Form().setVisible(true);
            }
        });
    }
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/image/logo2.png")));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Ders_Guncelle;
    private javax.swing.JButton btn_Kullanici_Guncelle;
    private javax.swing.JButton btn_Sifre;
    private javax.swing.JButton btn_Soru_Guncelle;
    private javax.swing.JButton btn_Soru_Guncelle2;
    private javax.swing.JButton btn_Soru_Turu;
    private javax.swing.JButton btn_Soru_Turu1;
    private javax.swing.JButton btn_Zorluk_Guncelle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private static javax.swing.JLabel lb_user;
    private static javax.swing.JDesktopPane mdi_Panel;
    private javax.swing.JPanel panel_Ders;
    private javax.swing.JPanel panel_Kullanici;
    private javax.swing.JPanel panel_Proje;
    private javax.swing.JPanel panel_Sifre;
    private javax.swing.JPanel panel_Sinav;
    private javax.swing.JPanel panel_Soru;
    private static javax.swing.JTabbedPane tabbed_Menu;
    // End of variables declaration//GEN-END:variables

    @Override
    public void BilgiYaz() {
    
     setUser(Kullanici.getAdi()+" "+Kullanici.getSoyadi());

      getLb_user().setText("-> "+getUser());
    }
}
