/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


import Presenter.OtomasyonaGirisPresenter;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.util.TimerTask;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.Timer;
import sun.applet.Main;

/**
 *
 * @author User
 */
public class Otomasyona_Giris_Form extends javax.swing.JFrame implements IViewOtomasyonaGiris {

   
 
    
    /**
     * Creates new form Otomasyona_Giris_Form
     */
    private static Otomasyona_Giris_Form frm = new Otomasyona_Giris_Form();
    
    public static Otomasyona_Giris_Form nesneURet(){
        return frm;
    }
    
    
    OtomasyonaGirisPresenter presenter;
    
    
    

    
    
    private Otomasyona_Giris_Form() {
    
        setResizable(false);
        
        initComponents();
    
     presenter= new   OtomasyonaGirisPresenter(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_baslik = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_cikis = new javax.swing.JButton();
        txt_kAdi = new javax.swing.JTextField();
        btn_giris = new javax.swing.JButton();
        txt_sifre = new javax.swing.JPasswordField();
        lbl_universite_logo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_kAdi1 = new javax.swing.JLabel();
        lbl_sifre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_kilit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quiz Maker Giriş Sayfası");
        setBackground(new java.awt.Color(153, 255, 255));
        setLocation(new java.awt.Point(500, 400));
        setLocationByPlatform(true);
        setName("Form"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_baslik.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_baslik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/baslik.png"))); // NOI18N
        lbl_baslik.setName("lbl_baslik"); // NOI18N
        getContentPane().add(lbl_baslik, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, -10, -1, 111));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cikis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cikis.png"))); // NOI18N
        btn_cikis.setText("Çıkış");
        btn_cikis.setName("btn_cikis"); // NOI18N
        btn_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cikisActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cikis, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 250, 40));

        txt_kAdi.setName("txt_kAdi"); // NOI18N
        txt_kAdi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_kAdiKeyPressed(evt);
            }
        });
        jPanel1.add(txt_kAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 242, 34));

        btn_giris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/giris.png"))); // NOI18N
        btn_giris.setText("Giriş");
        btn_giris.setBorder(null);
        btn_giris.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_giris.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btn_giris.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_giris.setName("btn_giris"); // NOI18N
        btn_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_girisActionPerformed(evt);
            }
        });
        jPanel1.add(btn_giris, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 250, 40));

        txt_sifre.setName("txt_sifre"); // NOI18N
        txt_sifre.setPreferredSize(new java.awt.Dimension(69, 22));
        txt_sifre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_sifreKeyPressed(evt);
            }
        });
        jPanel1.add(txt_sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 242, 34));

        lbl_universite_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dpu_logo.png"))); // NOI18N
        lbl_universite_logo.setName("lbl_universite_logo"); // NOI18N
        jPanel1.add(lbl_universite_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 101, 111));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel3.setText("Giriş");
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 165, -1));

        jLabel2.setText("Şifre:");
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        lbl_kAdi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kilit-1.png"))); // NOI18N
        lbl_kAdi1.setToolTipText("");
        lbl_kAdi1.setName("lbl_kAdi1"); // NOI18N
        jPanel1.add(lbl_kAdi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, 38));

        lbl_sifre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sifre-2.png"))); // NOI18N
        lbl_sifre.setToolTipText("");
        lbl_sifre.setName("lbl_sifre"); // NOI18N
        jPanel1.add(lbl_sifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, 38));

        jLabel4.setText("Kullanıcı Adı:");
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        lbl_kilit.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_kilit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kilit.png"))); // NOI18N
        lbl_kilit.setName("lbl_kilit"); // NOI18N
        jPanel1.add(lbl_kilit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 470, 600));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg2.png"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 1310, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_girisActionPerformed

        presenter.GirisYap();
      
       
   
    }//GEN-LAST:event_btn_girisActionPerformed

    private void btn_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cikisActionPerformed
         
        
        
    }//GEN-LAST:event_btn_cikisActionPerformed

    private void txt_kAdiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kAdiKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
        txt_sifre.requestFocus();  
        }
    }//GEN-LAST:event_txt_kAdiKeyPressed

    private void txt_sifreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sifreKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            
           presenter.GirisYap();
        }
    }//GEN-LAST:event_txt_sifreKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Otomasyona_Giris_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Otomasyona_Giris_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Otomasyona_Giris_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Otomasyona_Giris_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                
                
               new Otomasyona_Giris_Form().setVisible(true);
            }

           
        });
    }

    public static JTextField getTxt_kAdi() {
        return txt_kAdi;
    }

    public static void setTxt_kAdi(JTextField txt_kAdi) {
        Otomasyona_Giris_Form.txt_kAdi = txt_kAdi;
    }

    public static JPasswordField getTxt_sifre() {
        return txt_sifre;
    }

    public static void setTxt_sifre(JPasswordField txt_sifre) {
        Otomasyona_Giris_Form.txt_sifre = txt_sifre;
    }


 

    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_cikis;
    public javax.swing.JButton btn_giris;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lbl_baslik;
    public javax.swing.JLabel lbl_kAdi1;
    public javax.swing.JLabel lbl_kilit;
    public javax.swing.JLabel lbl_sifre;
    public javax.swing.JLabel lbl_universite_logo;
    private static javax.swing.JTextField txt_kAdi;
    private static javax.swing.JPasswordField txt_sifre;
    // End of variables declaration//GEN-END:variables

    @Override
    public void GirisIslemi(String mesaj) {
         JOptionPane.showConfirmDialog(null, mesaj,"Giriş Başarılı",JOptionPane.PLAIN_MESSAGE);
      
     
    }

    @Override
    public void Gir() {
      this.dispose();
    
    }

}
