package View;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Presenter.DerslikGuncellePresenter;
import com.sun.glass.events.KeyEvent;
import java.awt.Toolkit;
import static java.lang.String.valueOf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import org.eclipse.persistence.jpa.jpql.parser.DateTime;



public class Derslik_Guncelle_Form extends javax.swing.JInternalFrame implements IViewDerslikGuncelle {

  private static Derslik_Guncelle_Form form = new Derslik_Guncelle_Form();
  public static Derslik_Guncelle_Form yeniFormOlustur(){
      return form;
  }

private DerslikGuncellePresenter presenter;
    

    
    Connection baglanti = null;
    private  Derslik_Guncelle_Form() {

      presenter =new DerslikGuncellePresenter(this);
        setResizable(false);
        initComponents();
       
        lbl_Secilen.setVisible(false);
        txt_Arama.setText(null);
        presenter.tabloYenile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_Bina_Adi = new javax.swing.JTextField();
        txt_Salon_No = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_Salon_Kodu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_Salon_Kapasitesi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_Kaydet = new javax.swing.JButton();
        btn_Kapat = new javax.swing.JButton();
        btn_Kaydet1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablo_Derslik = new javax.swing.JTable();
        lbl_Secilen = new javax.swing.JLabel();
        btn_Yeni = new javax.swing.JButton();
        txt_Arama = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Derslik Bilgileri Güncelleme");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sinif.png"))); // NOI18N
        jLabel3.setText("DERSLİK GÜNCELLEME EKRANI");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Bina Adı:");

        txt_Bina_Adi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Bina_AdiKeyPressed(evt);
            }
        });

        txt_Salon_No.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Salon_NoKeyPressed(evt);
            }
        });

        jLabel5.setText("Salon No:");

        txt_Salon_Kodu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Salon_KoduKeyPressed(evt);
            }
        });

        jLabel6.setText("Sanon Kodu:");

        txt_Salon_Kapasitesi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Salon_KapasitesiKeyPressed(evt);
            }
        });

        jLabel7.setText("Salon Kapasitesi:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(26, 26, 26)
                        .addComponent(txt_Salon_Kapasitesi, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(26, 26, 26)
                        .addComponent(txt_Salon_Kodu, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26)
                        .addComponent(txt_Salon_No, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addComponent(txt_Bina_Adi, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Bina_Adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Salon_No, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_Salon_Kodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_Salon_Kapasitesi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_Kaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Kaydet24x24.png"))); // NOI18N
        btn_Kaydet.setText("Kayıt Ekle / Güncelle");
        btn_Kaydet.setName("btn_Giris"); // NOI18N
        btn_Kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KaydetActionPerformed(evt);
            }
        });

        btn_Kapat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sil24x24.png"))); // NOI18N
        btn_Kapat.setText("Kapat");
        btn_Kapat.setName("btn_Cikis"); // NOI18N
        btn_Kapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KapatActionPerformed(evt);
            }
        });

        btn_Kaydet1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sil32x32.png"))); // NOI18N
        btn_Kaydet1.setText("Kaydı Sil");
        btn_Kaydet1.setName("btn_Giris"); // NOI18N
        btn_Kaydet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Kaydet1ActionPerformed(evt);
            }
        });

        tablo_Derslik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Bina Adı", "Salon No", "Salon Kodu", "Derslik Kapasitesi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablo_Derslik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablo_DerslikMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablo_Derslik);
        if (tablo_Derslik.getColumnModel().getColumnCount() > 0) {
            tablo_Derslik.getColumnModel().getColumn(0).setResizable(false);
        }

        btn_Yeni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/yenile.png"))); // NOI18N
        btn_Yeni.setText("Formu Temizle");
        btn_Yeni.setName("btn_Giris"); // NOI18N
        btn_Yeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_YeniActionPerformed(evt);
            }
        });

        txt_Arama.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_AramaCaretUpdate(evt);
            }
        });
        txt_Arama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_AramaKeyPressed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/arama.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(422, 422, 422))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btn_Yeni, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(btn_Kaydet1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Kapat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_Secilen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_Arama, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_Arama)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_Secilen, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Kaydet1)
                    .addComponent(btn_Kapat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Yeni, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     

                                           
    
    private void btn_KaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KaydetActionPerformed
        // TODO add your handling code here:
 presenter.tablodanVeriGuncelle();
 presenter.tabloYenile();
    }//GEN-LAST:event_btn_KaydetActionPerformed

    private void btn_KapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KapatActionPerformed
        // TODO add your handling code here:
        dispose();

    }//GEN-LAST:event_btn_KapatActionPerformed

    private void btn_Kaydet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Kaydet1ActionPerformed
        // TODO add your handling code here:
         presenter.tablodanVeriSilme();
    }//GEN-LAST:event_btn_Kaydet1ActionPerformed

    private void tablo_DerslikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablo_DerslikMouseClicked
        // TODO add your handling code here:
         presenter.tablodanVeriSecme();
    }//GEN-LAST:event_tablo_DerslikMouseClicked

    private void btn_YeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_YeniActionPerformed
        // TODO add your handling code here:
        txt_Arama.setText(null);
         presenter.tabloYenile();
    }//GEN-LAST:event_btn_YeniActionPerformed

    private void txt_Bina_AdiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Bina_AdiKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_Bina_AdiKeyPressed

    private void txt_AramaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_AramaKeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txt_AramaKeyPressed

    private void txt_AramaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_AramaCaretUpdate
        // TODO add your handling code here:
        presenter.tabloYenile();
    }//GEN-LAST:event_txt_AramaCaretUpdate

    private void txt_Salon_NoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Salon_NoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Salon_NoKeyPressed

    private void txt_Salon_KoduKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Salon_KoduKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Salon_KoduKeyPressed

    private void txt_Salon_KapasitesiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Salon_KapasitesiKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Salon_KapasitesiKeyPressed

    public static JLabel getLbl_Secilen() {
        return lbl_Secilen;
    }

    public static void setLbl_Secilen(JLabel lbl_Secilen) {
        Derslik_Guncelle_Form.lbl_Secilen = lbl_Secilen;
    }

    public static JTable getTablo_Derslik() {
        return tablo_Derslik;
    }

    public static void setTablo_Derslik(JTable tablo_Derslik) {
        Derslik_Guncelle_Form.tablo_Derslik = tablo_Derslik;
    }

    public static JTextField getTxt_Arama() {
        return txt_Arama;
    }

    public static void setTxt_Arama(JTextField txt_Arama) {
        Derslik_Guncelle_Form.txt_Arama = txt_Arama;
    }

    public static JTextField getTxt_Bina_Adi() {
        return txt_Bina_Adi;
    }

    public static void setTxt_Bina_Adi(JTextField txt_Bina_Adi) {
        Derslik_Guncelle_Form.txt_Bina_Adi = txt_Bina_Adi;
    }

    public static JTextField getTxt_Salon_Kapasitesi() {
        return txt_Salon_Kapasitesi;
    }

    public static void setTxt_Salon_Kapasitesi(JTextField txt_Salon_Kapasitesi) {
        Derslik_Guncelle_Form.txt_Salon_Kapasitesi = txt_Salon_Kapasitesi;
    }

    public static JTextField getTxt_Salon_Kodu() {
        return txt_Salon_Kodu;
    }

    public static void setTxt_Salon_Kodu(JTextField txt_Salon_Kodu) {
        Derslik_Guncelle_Form.txt_Salon_Kodu = txt_Salon_Kodu;
    }

    public static JTextField getTxt_Salon_No() {
        return txt_Salon_No;
    }

    public static void setTxt_Salon_No(JTextField txt_Salon_No) {
        Derslik_Guncelle_Form.txt_Salon_No = txt_Salon_No;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Kapat;
    private javax.swing.JButton btn_Kaydet;
    private javax.swing.JButton btn_Kaydet1;
    private javax.swing.JButton btn_Yeni;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JLabel lbl_Secilen;
    private static javax.swing.JTable tablo_Derslik;
    private static javax.swing.JTextField txt_Arama;
    private static javax.swing.JTextField txt_Bina_Adi;
    private static javax.swing.JTextField txt_Salon_Kapasitesi;
    private static javax.swing.JTextField txt_Salon_Kodu;
    private static javax.swing.JTextField txt_Salon_No;
    // End of variables declaration//GEN-END:variables
}
