package View;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
*/
import Presenter.GozetmenGuncellePresenter;
import com.sun.glass.events.KeyEvent;
import java.awt.Toolkit;
import static java.lang.String.valueOf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import org.eclipse.persistence.jpa.jpql.parser.DateTime;



public class Gozetmen_Guncelle_Form extends javax.swing.JInternalFrame implements IViewGozetmenGuncelle {

    private GozetmenGuncellePresenter presenter;
    
    private static Gozetmen_Guncelle_Form form = new Gozetmen_Guncelle_Form();
    public static Gozetmen_Guncelle_Form yeniFormOlustur(){
        return form;
    }
    



    

    
    Connection baglanti = null;
    private Gozetmen_Guncelle_Form() {

       
        setResizable(false);
        initComponents();
       
        presenter = new GozetmenGuncellePresenter(this);
        lbl_Secilen.setVisible(false);
        txt_Arama.setText(null);

        presenter.tabloYenile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_Adi_Soyadi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cm_Gorev = new javax.swing.JComboBox<String>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ls_Dersler = new javax.swing.JList<String>();
        jScrollPane3 = new javax.swing.JScrollPane();
        ls_Gorevlendirilen_Ders = new javax.swing.JList<String>();
        lb_Ders_Liste = new javax.swing.JLabel();
        lb_Gorevlendirilen_Dersler = new javax.swing.JLabel();
        btn_Ekle = new javax.swing.JButton();
        btn_Cikar = new javax.swing.JButton();
        btn_Kaydet = new javax.swing.JButton();
        btn_Kapat = new javax.swing.JButton();
        btn_Kaydet1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablo_Gozetmen = new javax.swing.JTable();
        lbl_Secilen = new javax.swing.JLabel();
        btn_Yeni = new javax.swing.JButton();
        txt_Arama = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Görevli Bilgileri Güncelleme");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/gozetmen.png"))); // NOI18N
        jLabel3.setText("ÖĞRETİM ÜYESİ VE GÖZETMEN GÜNCELLEME EKRANI");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Adı Soyadı:");

        txt_Adi_Soyadi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Adi_SoyadiKeyPressed(evt);
            }
        });

        jLabel5.setText("Görevi:");

        cm_Gorev.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gözetmen", "Öğretim Üyesi" }));
        cm_Gorev.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cm_GorevPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jScrollPane2.setViewportView(ls_Dersler);

        jScrollPane3.setViewportView(ls_Gorevlendirilen_Ders);

        lb_Ders_Liste.setText("Ders Listesi:");

        lb_Gorevlendirilen_Dersler.setText("Görevlendirilen Dersler:");

        btn_Ekle.setText("Ekle ->");
        btn_Ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EkleActionPerformed(evt);
            }
        });

        btn_Cikar.setText("<- Çıkar");
        btn_Cikar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CikarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Adi_Soyadi)
                            .addComponent(cm_Gorev, 0, 185, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Cikar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Ekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lb_Ders_Liste)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_Gorevlendirilen_Dersler)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Adi_Soyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cm_Gorev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Ders_Liste)
                    .addComponent(lb_Gorevlendirilen_Dersler))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btn_Ekle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Cikar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        btn_Kaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Kaydet24x24.png"))); // NOI18N
        btn_Kaydet.setText("Kayıt Ekle / Güncelle");
        btn_Kaydet.setName("btn_Giris"); // NOI18N
        btn_Kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KaydetActionPerformed(evt);
            }
        });

        btn_Kapat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sil24x24.png"))); // NOI18N
        btn_Kapat.setText("Kapat");
        btn_Kapat.setName("btn_Cikis"); // NOI18N
        btn_Kapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KapatActionPerformed(evt);
            }
        });

        btn_Kaydet1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sil32x32.png"))); // NOI18N
        btn_Kaydet1.setText("Kaydı Sil");
        btn_Kaydet1.setName("btn_Giris"); // NOI18N
        btn_Kaydet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Kaydet1ActionPerformed(evt);
            }
        });

        tablo_Gozetmen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Adı Soyadı", "Görevi", "Verdiği Dersler"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablo_Gozetmen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablo_GozetmenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablo_Gozetmen);
        if (tablo_Gozetmen.getColumnModel().getColumnCount() > 0) {
            tablo_Gozetmen.getColumnModel().getColumn(0).setResizable(false);
        }

        btn_Yeni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/yenile.png"))); // NOI18N
        btn_Yeni.setText("Formu Temizle");
        btn_Yeni.setName("btn_Giris"); // NOI18N
        btn_Yeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_YeniActionPerformed(evt);
            }
        });

        txt_Arama.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_AramaCaretUpdate(evt);
            }
        });
        txt_Arama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_AramaKeyPressed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/arama.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_Secilen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_Arama, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btn_Yeni, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(btn_Kaydet1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Kapat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_Arama)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_Secilen, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Kaydet1)
                    .addComponent(btn_Kapat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Yeni, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     
     
            
        
                                           
    
    private void btn_KaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KaydetActionPerformed
        // TODO add your handling code here:
    presenter.tablodanVeriGuncelle();
    presenter.tabloYenile();
    }//GEN-LAST:event_btn_KaydetActionPerformed

    private void btn_KapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KapatActionPerformed
        // TODO add your handling code here:
        dispose();

    }//GEN-LAST:event_btn_KapatActionPerformed

    private void btn_Kaydet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Kaydet1ActionPerformed
        // TODO add your handling code here:
        presenter.tablodanVeriSilme();
    }//GEN-LAST:event_btn_Kaydet1ActionPerformed

    private void tablo_GozetmenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablo_GozetmenMouseClicked
        // TODO add your handling code here:
        presenter.tablodanVeriSecme();
    }//GEN-LAST:event_tablo_GozetmenMouseClicked

    private void btn_YeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_YeniActionPerformed
        // TODO add your handling code here:
        txt_Arama.setText(null);
        presenter.tabloYenile();
    }//GEN-LAST:event_btn_YeniActionPerformed

    private void txt_Adi_SoyadiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Adi_SoyadiKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_Adi_SoyadiKeyPressed

    private void txt_AramaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_AramaKeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txt_AramaKeyPressed

    private void txt_AramaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_AramaCaretUpdate
        // TODO add your handling code here:
       presenter.tabloYenile();
    }//GEN-LAST:event_txt_AramaCaretUpdate

    private void cm_GorevPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cm_GorevPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
      presenter.gorevMenu();
    }//GEN-LAST:event_cm_GorevPopupMenuWillBecomeInvisible

    private void btn_EkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EkleActionPerformed
        // TODO add your handling code here:
            
 presenter.btnEkle();
    }//GEN-LAST:event_btn_EkleActionPerformed

    private void btn_CikarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CikarActionPerformed
        // TODO add your handling code here:
           presenter.btnCikar();
    }//GEN-LAST:event_btn_CikarActionPerformed

    public static JLabel getLbl_Secilen() {
        return lbl_Secilen;
    }

    public static void setLbl_Secilen(JLabel lbl_Secilen) {
        Gozetmen_Guncelle_Form.lbl_Secilen = lbl_Secilen;
    }

    public static JTextField getTxt_Arama() {
        return txt_Arama;
    }

    public static void setTxt_Arama(JTextField txt_Arama) {
        Gozetmen_Guncelle_Form.txt_Arama = txt_Arama;
    }

    public static JComboBox<String> getCm_Gorev() {
        return cm_Gorev;
    }

    public static void setCm_Gorev(JComboBox<String> cm_Gorev) {
        Gozetmen_Guncelle_Form.cm_Gorev = cm_Gorev;
    }

    public static JLabel getLb_Ders_Liste() {
        return lb_Ders_Liste;
    }

    public static void setLb_Ders_Liste(JLabel lb_Ders_Liste) {
        Gozetmen_Guncelle_Form.lb_Ders_Liste = lb_Ders_Liste;
    }

    public static JLabel getLb_Gorevlendirilen_Dersler() {
        return lb_Gorevlendirilen_Dersler;
    }

    public static void setLb_Gorevlendirilen_Dersler(JLabel lb_Gorevlendirilen_Dersler) {
        Gozetmen_Guncelle_Form.lb_Gorevlendirilen_Dersler = lb_Gorevlendirilen_Dersler;
    }

  

    public static JList<String> getLs_Dersler() {
        return ls_Dersler;
    }

    public static void setLs_Dersler(JList<String> ls_Dersler) {
        Gozetmen_Guncelle_Form.ls_Dersler = ls_Dersler;
    }

    public static JList<String> getLs_Gorevlendirilen_Ders() {
        return ls_Gorevlendirilen_Ders;
    }

    public static void setLs_Gorevlendirilen_Ders(JList<String> ls_Gorevlendirilen_Ders) {
        Gozetmen_Guncelle_Form.ls_Gorevlendirilen_Ders = ls_Gorevlendirilen_Ders;
    }

    public static JTable getTablo_Gozetmen() {
        return tablo_Gozetmen;
    }

    public static void setTablo_Gozetmen(JTable tablo_Gozetmen) {
        Gozetmen_Guncelle_Form.tablo_Gozetmen = tablo_Gozetmen;
    }

    public static JTextField getTxt_Adi_Soyadi() {
        return txt_Adi_Soyadi;
    }

    public static void setTxt_Adi_Soyadi(JTextField txt_Adi_Soyadi) {
        Gozetmen_Guncelle_Form.txt_Adi_Soyadi = txt_Adi_Soyadi;
    }

    public static JButton getBtn_Cikar() {
        return btn_Cikar;
    }

    public static void setBtn_Cikar(JButton btn_Cikar) {
        Gozetmen_Guncelle_Form.btn_Cikar = btn_Cikar;
    }

    public static JButton getBtn_Ekle() {
        return btn_Ekle;
    }

    public static void setBtn_Ekle(JButton btn_Ekle) {
        Gozetmen_Guncelle_Form.btn_Ekle = btn_Ekle;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton btn_Cikar;
    private static javax.swing.JButton btn_Ekle;
    private javax.swing.JButton btn_Kapat;
    private javax.swing.JButton btn_Kaydet;
    private javax.swing.JButton btn_Kaydet1;
    private javax.swing.JButton btn_Yeni;
    private static javax.swing.JComboBox<String> cm_Gorev;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private static javax.swing.JLabel lb_Ders_Liste;
    private static javax.swing.JLabel lb_Gorevlendirilen_Dersler;
    private static javax.swing.JLabel lbl_Secilen;
    private static javax.swing.JList<String> ls_Dersler;
    private static javax.swing.JList<String> ls_Gorevlendirilen_Ders;
    private static javax.swing.JTable tablo_Gozetmen;
    private static javax.swing.JTextField txt_Adi_Soyadi;
    private static javax.swing.JTextField txt_Arama;
    // End of variables declaration//GEN-END:variables
}
