/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;



import Presenter.SoruGuncellePresenter;
import com.sun.glass.events.KeyEvent;
import java.awt.Toolkit;
import static java.lang.String.valueOf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import org.eclipse.persistence.jpa.jpql.parser.DateTime;


public class Soru_Guncelle_Form extends javax.swing.JInternalFrame implements IViewSoruGuncelle {

   private static Soru_Guncelle_Form form = new Soru_Guncelle_Form();
   
   public static Soru_Guncelle_Form yeniFormOlustur(){
       return form;
   }

   private SoruGuncellePresenter presenter;
   

    private Soru_Guncelle_Form() {
     
      presenter = new SoruGuncellePresenter(this);
        setResizable(false);
        initComponents();
        

        lbl_Secilen.setVisible(false);
        txt_Arama.setText(null);

        presenter.cm_Ders_Doldurma();
        presenter.cm_Ders_Doldurma();
       presenter.cm_Soru_Tip_Doldurma();
        presenter.cm_Zorluk_Turu_Doldurma();
        
       presenter.tabloYenile();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lb_Soru = new javax.swing.JLabel();
        txt_soru = new javax.swing.JTextField();
        txt_cevap_1 = new javax.swing.JTextField();
        lb_Cevap_1 = new javax.swing.JLabel();
        cm_Ders = new javax.swing.JComboBox<String>();
        cm_Soru_Tip = new javax.swing.JComboBox<String>();
        cm_Zorluk_Tip = new javax.swing.JComboBox<String>();
        cm_Sayi = new javax.swing.JComboBox<String>();
        txt_cevap_2 = new javax.swing.JTextField();
        lb_Cevap_2 = new javax.swing.JLabel();
        txt_cevap_3 = new javax.swing.JTextField();
        lb_Cevap_3 = new javax.swing.JLabel();
        txt_cevap_4 = new javax.swing.JTextField();
        lb_Cevap_4 = new javax.swing.JLabel();
        txt_cevap_5 = new javax.swing.JTextField();
        lb_Cevap_5 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lb_Sayi = new javax.swing.JLabel();
        lb_Dogru_Cevap = new javax.swing.JLabel();
        txt_Dogru_Cevap = new javax.swing.JTextField();
        cm_Dogru_Cevap = new javax.swing.JComboBox<String>();
        btn_Kaydet = new javax.swing.JButton();
        btn_Kapat = new javax.swing.JButton();
        btn_Kaydet1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablo_Soru = new javax.swing.JTable();
        btn_Yeni = new javax.swing.JButton();
        txt_Arama = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lbl_Secilen = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);
        setTitle("Soru Güncelleme");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/soru_guncelle.png"))); // NOI18N
        jLabel3.setText("SORU GÜNCELLEME EKRANI");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_Soru.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_Soru.setText("Soru :");
        lb_Soru.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txt_soru.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_soru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_soruKeyPressed(evt);
            }
        });

        txt_cevap_1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_cevap_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cevap_1KeyPressed(evt);
            }
        });

        lb_Cevap_1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_Cevap_1.setText("Cevap :");
        lb_Cevap_1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        cm_Ders.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cm_DersİtemStateChanged(evt);
            }
        });
        cm_Ders.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cm_DersPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cm_Ders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cm_DersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cm_DersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cm_DersMouseExited(evt);
            }
        });

        cm_Soru_Tip.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cm_Soru_TipİtemStateChanged(evt);
            }
        });
        cm_Soru_Tip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cm_Soru_TipMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cm_Soru_TipMouseReleased(evt);
            }
        });

        cm_Sayi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "4", "5" }));
        cm_Sayi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cm_SayiİtemStateChanged(evt);
            }
        });

        txt_cevap_2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_cevap_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cevap_2KeyPressed(evt);
            }
        });

        lb_Cevap_2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_Cevap_2.setText("b)");
        lb_Cevap_2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txt_cevap_3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_cevap_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cevap_3KeyPressed(evt);
            }
        });

        lb_Cevap_3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_Cevap_3.setText("c)");
        lb_Cevap_3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txt_cevap_4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_cevap_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cevap_4KeyPressed(evt);
            }
        });

        lb_Cevap_4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_Cevap_4.setText("d)");
        lb_Cevap_4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txt_cevap_5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_cevap_5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cevap_5KeyPressed(evt);
            }
        });

        lb_Cevap_5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_Cevap_5.setText("e)");
        lb_Cevap_5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel5.setText("Ders:");

        jLabel6.setText("Zorluk:");

        jLabel7.setText("Soru Tiipi:");

        lb_Sayi.setText("Şık Sayısı:");

        lb_Dogru_Cevap.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_Dogru_Cevap.setText("Doğru Cevap:");
        lb_Dogru_Cevap.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txt_Dogru_Cevap.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_Dogru_Cevap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_Dogru_CevapKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cm_Ders, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cm_Zorluk_Tip, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lb_Sayi)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cm_Sayi, 0, 120, Short.MAX_VALUE)
                            .addComponent(cm_Soru_Tip, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lb_Cevap_5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_Cevap_4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_Cevap_3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_Cevap_2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_Cevap_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_Soru, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_Dogru_Cevap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_Dogru_Cevap, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cm_Dogru_Cevap, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_cevap_5)
                            .addComponent(txt_cevap_4)
                            .addComponent(txt_cevap_3)
                            .addComponent(txt_cevap_2)
                            .addComponent(txt_cevap_1)
                            .addComponent(txt_soru, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cm_Ders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cm_Soru_Tip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cm_Sayi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cm_Zorluk_Tip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(lb_Sayi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Soru)
                    .addComponent(txt_soru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Cevap_1)
                    .addComponent(txt_cevap_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Cevap_2)
                    .addComponent(txt_cevap_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Cevap_3)
                    .addComponent(txt_cevap_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cevap_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_Cevap_4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cevap_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_Cevap_5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Dogru_Cevap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_Dogru_Cevap)
                    .addComponent(cm_Dogru_Cevap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_Kaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Kaydet24x24.png"))); // NOI18N
        btn_Kaydet.setText("Kayıt Ekle / Güncelle");
        btn_Kaydet.setName("btn_Giris"); // NOI18N
        btn_Kaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KaydetActionPerformed(evt);
            }
        });

        btn_Kapat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sil24x24.png"))); // NOI18N
        btn_Kapat.setText("Kapat");
        btn_Kapat.setName("btn_Cikis"); // NOI18N
        btn_Kapat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KapatActionPerformed(evt);
            }
        });

        btn_Kaydet1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sil32x32.png"))); // NOI18N
        btn_Kaydet1.setText("Kaydı Sil");
        btn_Kaydet1.setName("btn_Giris"); // NOI18N
        btn_Kaydet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Kaydet1ActionPerformed(evt);
            }
        });

        tablo_Soru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Soru", "Cevap", "Doğru Cevap"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablo_Soru.setAutoscrolls(false);
        tablo_Soru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablo_SoruMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablo_Soru);
        if (tablo_Soru.getColumnModel().getColumnCount() > 0) {
            tablo_Soru.getColumnModel().getColumn(0).setResizable(false);
        }

        btn_Yeni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/yenile.png"))); // NOI18N
        btn_Yeni.setText("Formu Temizle");
        btn_Yeni.setName("btn_Giris"); // NOI18N
        btn_Yeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_YeniActionPerformed(evt);
            }
        });

        txt_Arama.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_AramaCaretUpdate(evt);
            }
        });
        txt_Arama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_AramaKeyPressed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/arama.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_Secilen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(txt_Arama))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btn_Yeni, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btn_Kaydet1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Kapat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txt_Arama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_Secilen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Kaydet1)
                    .addComponent(btn_Kapat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Yeni, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btn_KaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KaydetActionPerformed
        // TODO add your handling code here:
        presenter.tablodanVeriGuncelle();

    }//GEN-LAST:event_btn_KaydetActionPerformed

    private void btn_KapatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KapatActionPerformed
        // TODO add your handling code here:
        dispose();

    }//GEN-LAST:event_btn_KapatActionPerformed

    private void btn_Kaydet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Kaydet1ActionPerformed
        // TODO add your handling code here:
        presenter.tablodanVeriSilme();
    }//GEN-LAST:event_btn_Kaydet1ActionPerformed

    private void tablo_SoruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablo_SoruMouseClicked
        // TODO add your handling code here:
        presenter.tablodanVeriSecme();
    }//GEN-LAST:event_tablo_SoruMouseClicked

    private void btn_YeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_YeniActionPerformed
        // TODO add your handling code here:
        txt_Arama.setText(null);
        presenter.tabloYenile();
    }//GEN-LAST:event_btn_YeniActionPerformed

    private void txt_soruKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_soruKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_soruKeyPressed

    private void txt_AramaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_AramaKeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_txt_AramaKeyPressed

    private void txt_AramaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_AramaCaretUpdate
        // TODO add your handling code here:
      presenter.tabloYenile();
    }//GEN-LAST:event_txt_AramaCaretUpdate

    private void txt_cevap_1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cevap_1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cevap_1KeyPressed

    private void txt_cevap_2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cevap_2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cevap_2KeyPressed

    private void txt_cevap_3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cevap_3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cevap_3KeyPressed

    private void txt_cevap_4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cevap_4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cevap_4KeyPressed

    private void txt_cevap_5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cevap_5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cevap_5KeyPressed

    private void txt_Dogru_CevapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Dogru_CevapKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Dogru_CevapKeyPressed

    private void cm_Soru_TipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cm_Soru_TipMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cm_Soru_TipMouseClicked

    private void cm_Soru_TipMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cm_Soru_TipMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_cm_Soru_TipMouseReleased

    private void cm_Soru_TipİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cm_Soru_TipİtemStateChanged
        // TODO add your handling code here:
        if (cm_Soru_Tip.getSelectedItem().equals("ÇOKTAN SEÇMELİ")) {
            lb_Sayi.setVisible(true);
            cm_Sayi.setVisible(true);
            lb_Cevap_1.setText("a)");
            cm_Dogru_Cevap.setVisible(true);
            lb_Dogru_Cevap.setVisible(true);
            txt_Dogru_Cevap.setVisible(false);
            txt_cevap_1.setVisible(true);
            txt_cevap_2.setVisible(true);
            txt_cevap_3.setVisible(true);
            txt_cevap_4.setVisible(false);
            txt_cevap_5.setVisible(false);
            lb_Cevap_1.setVisible(true);
            lb_Cevap_2.setVisible(true);
            lb_Cevap_2.setVisible(true);
            lb_Cevap_3.setVisible(true);
            lb_Cevap_4.setVisible(false);
            lb_Cevap_5.setVisible(false);
            cm_Dogru_Cevap.removeAllItems();
            cm_Dogru_Cevap.addItem("a");
            cm_Dogru_Cevap.addItem("b");
            cm_Dogru_Cevap.addItem("c");

        } else if (cm_Soru_Tip.getSelectedItem().equals("KLASİK") || cm_Soru_Tip.getSelectedItem().equals("BOŞLUK DOLDURMA")) {
            lb_Sayi.setVisible(false);
            cm_Sayi.setVisible(false);
            lb_Cevap_1.setText("Cevap:");
            cm_Dogru_Cevap.setVisible(false);
            lb_Dogru_Cevap.setVisible(true);
            txt_Dogru_Cevap.setVisible(true);
            txt_cevap_1.setVisible(false);
            txt_cevap_2.setVisible(false);
            txt_cevap_3.setVisible(false);
            txt_cevap_4.setVisible(false);
            txt_cevap_5.setVisible(false);
            lb_Cevap_1.setVisible(false);
            lb_Cevap_2.setVisible(false);
            lb_Cevap_3.setVisible(false);
            lb_Cevap_4.setVisible(false);
            lb_Cevap_5.setVisible(false);

        } else if (cm_Soru_Tip.getSelectedItem().equals("DOĞRU YANLIŞ")) {
            lb_Sayi.setVisible(false);
            cm_Sayi.setVisible(false);
            lb_Cevap_1.setVisible(false);
            cm_Dogru_Cevap.setVisible(true);
            lb_Dogru_Cevap.setVisible(true);
            txt_Dogru_Cevap.setVisible(false);
            txt_cevap_1.setVisible(false);
            txt_cevap_2.setVisible(false);
            txt_cevap_3.setVisible(false);
            txt_cevap_4.setVisible(false);
            txt_cevap_5.setVisible(false);
            lb_Cevap_2.setVisible(false);
            lb_Cevap_3.setVisible(false);
            lb_Cevap_4.setVisible(false);
            lb_Cevap_5.setVisible(false);
            cm_Dogru_Cevap.removeAllItems();
            cm_Dogru_Cevap.addItem("Doğru");
            cm_Dogru_Cevap.addItem("Yanlış");

        }
    }//GEN-LAST:event_cm_Soru_TipİtemStateChanged

    private void cm_SayiİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cm_SayiİtemStateChanged
        // TODO add your handling code here:
        if (cm_Sayi.getSelectedItem().equals("3")) {
            lb_Cevap_4.setVisible(false);
            lb_Cevap_5.setVisible(false);
            txt_cevap_4.setVisible(false);
            txt_cevap_5.setVisible(false);
            cm_Dogru_Cevap.removeAllItems();
            cm_Dogru_Cevap.addItem("a");
            cm_Dogru_Cevap.addItem("b");
            cm_Dogru_Cevap.addItem("c");

        } else if (cm_Sayi.getSelectedItem().equals("4")) {
            lb_Cevap_4.setVisible(true);
            lb_Cevap_5.setVisible(false);
            txt_cevap_4.setVisible(true);
            txt_cevap_5.setVisible(false);
            cm_Dogru_Cevap.removeAllItems();
            cm_Dogru_Cevap.addItem("a");
            cm_Dogru_Cevap.addItem("b");
            cm_Dogru_Cevap.addItem("c");
            cm_Dogru_Cevap.addItem("d");

        } else if (cm_Sayi.getSelectedItem().equals("5")) {
            lb_Cevap_4.setVisible(true);
            lb_Cevap_5.setVisible(true);
            txt_cevap_4.setVisible(true);
            txt_cevap_5.setVisible(true);
            cm_Dogru_Cevap.removeAllItems();
            cm_Dogru_Cevap.addItem("a");
            cm_Dogru_Cevap.addItem("b");
            cm_Dogru_Cevap.addItem("c");
            cm_Dogru_Cevap.addItem("d");
            cm_Dogru_Cevap.addItem("e");
        }


    }//GEN-LAST:event_cm_SayiİtemStateChanged

    
    private void cm_DersİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cm_DersİtemStateChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cm_DersİtemStateChanged

    private void cm_DersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cm_DersMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cm_DersMouseExited

    private void cm_DersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cm_DersMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cm_DersMouseClicked

    private void cm_DersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cm_DersMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cm_DersMouseEntered

    private void cm_DersPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cm_DersPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
       presenter.tabloYenile();
    }//GEN-LAST:event_cm_DersPopupMenuWillBecomeInvisible

    public static JComboBox<String> getCm_Ders() {
        return cm_Ders;
    }

    public static void setCm_Ders(JComboBox<String> cm_Ders) {
        Soru_Guncelle_Form.cm_Ders = cm_Ders;
    }

    public static JComboBox<String> getCm_Zorluk_Tip() {
        return cm_Zorluk_Tip;
    }

    public static void setCm_Zorluk_Tip(JComboBox<String> cm_Zorluk_Tip) {
        Soru_Guncelle_Form.cm_Zorluk_Tip = cm_Zorluk_Tip;
    }

    public static JComboBox<String> getCm_Soru_Tip() {
        return cm_Soru_Tip;
    }

    public static void setCm_Soru_Tip(JComboBox<String> cm_Soru_Tip) {
        Soru_Guncelle_Form.cm_Soru_Tip = cm_Soru_Tip;
    }

    public static JComboBox<String> getCm_Dogru_Cevap() {
        return cm_Dogru_Cevap;
    }

    public static void setCm_Dogru_Cevap(JComboBox<String> cm_Dogru_Cevap) {
        Soru_Guncelle_Form.cm_Dogru_Cevap = cm_Dogru_Cevap;
    }

    public static JComboBox<String> getCm_Sayi() {
        return cm_Sayi;
    }

    public static void setCm_Sayi(JComboBox<String> cm_Sayi) {
        Soru_Guncelle_Form.cm_Sayi = cm_Sayi;
    }

    public static JLabel getLbl_Secilen() {
        return lbl_Secilen;
    }

    public static void setLbl_Secilen(JLabel lbl_Secilen) {
        Soru_Guncelle_Form.lbl_Secilen = lbl_Secilen;
    }

    public static JTable getTablo_Soru() {
        return tablo_Soru;
    }

    public static void setTablo_Soru(JTable tablo_Soru) {
        Soru_Guncelle_Form.tablo_Soru = tablo_Soru;
    }

    public static JTextField getTxt_Arama() {
        return txt_Arama;
    }

    public static void setTxt_Arama(JTextField txt_Arama) {
        Soru_Guncelle_Form.txt_Arama = txt_Arama;
    }

    public static JTextField getTxt_Dogru_Cevap() {
        return txt_Dogru_Cevap;
    }

    public static void setTxt_Dogru_Cevap(JTextField txt_Dogru_Cevap) {
        Soru_Guncelle_Form.txt_Dogru_Cevap = txt_Dogru_Cevap;
    }

    public static JTextField getTxt_cevap_1() {
        return txt_cevap_1;
    }

    public static void setTxt_cevap_1(JTextField txt_cevap_1) {
        Soru_Guncelle_Form.txt_cevap_1 = txt_cevap_1;
    }

    public static JTextField getTxt_cevap_2() {
        return txt_cevap_2;
    }

    public static void setTxt_cevap_2(JTextField txt_cevap_2) {
        Soru_Guncelle_Form.txt_cevap_2 = txt_cevap_2;
    }

    public static JTextField getTxt_cevap_3() {
        return txt_cevap_3;
    }

    public static void setTxt_cevap_3(JTextField txt_cevap_3) {
        Soru_Guncelle_Form.txt_cevap_3 = txt_cevap_3;
    }

    public static JTextField getTxt_cevap_4() {
        return txt_cevap_4;
    }

    public static void setTxt_cevap_4(JTextField txt_cevap_4) {
        Soru_Guncelle_Form.txt_cevap_4 = txt_cevap_4;
    }

    public static JTextField getTxt_cevap_5() {
        return txt_cevap_5;
    }

    public static void setTxt_cevap_5(JTextField txt_cevap_5) {
        Soru_Guncelle_Form.txt_cevap_5 = txt_cevap_5;
    }

    public static JTextField getTxt_soru() {
        return txt_soru;
    }

    public static void setTxt_soru(JTextField txt_soru) {
        Soru_Guncelle_Form.txt_soru = txt_soru;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Kapat;
    private javax.swing.JButton btn_Kaydet;
    private javax.swing.JButton btn_Kaydet1;
    private javax.swing.JButton btn_Yeni;
    private static javax.swing.JComboBox<String> cm_Ders;
    private static javax.swing.JComboBox<String> cm_Dogru_Cevap;
    private static javax.swing.JComboBox<String> cm_Sayi;
    private static javax.swing.JComboBox<String> cm_Soru_Tip;
    private static javax.swing.JComboBox<String> cm_Zorluk_Tip;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_Cevap_1;
    private javax.swing.JLabel lb_Cevap_2;
    private javax.swing.JLabel lb_Cevap_3;
    private javax.swing.JLabel lb_Cevap_4;
    private javax.swing.JLabel lb_Cevap_5;
    private javax.swing.JLabel lb_Dogru_Cevap;
    private javax.swing.JLabel lb_Sayi;
    private javax.swing.JLabel lb_Soru;
    private static javax.swing.JLabel lbl_Secilen;
    private static javax.swing.JTable tablo_Soru;
    private static javax.swing.JTextField txt_Arama;
    private static javax.swing.JTextField txt_Dogru_Cevap;
    private static javax.swing.JTextField txt_cevap_1;
    private static javax.swing.JTextField txt_cevap_2;
    private static javax.swing.JTextField txt_cevap_3;
    private static javax.swing.JTextField txt_cevap_4;
    private static javax.swing.JTextField txt_cevap_5;
    private static javax.swing.JTextField txt_soru;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mesaj(String mesaj, String baslik) {
      JOptionPane.showConfirmDialog(null, mesaj, baslik, JOptionPane.DEFAULT_OPTION);
                  
    
    }
}
